# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html for more information

# [sncast.myprofile1]                                    # Define a profile name
# url = "http://127.0.0.1:5050/"                         # Url of the RPC provider
# accounts_file = "../account-file"                      # Path to the file with the account data
# account = "mainuser"                                   # Account from `accounts_file` or default account file that will be used for the transactions
# keystore = "~/keystore"                                # Path to the keystore file
# wait_params = { timeout = 500, retry_interval = 10 }   # Wait for submitted transaction parameters
# block_explorer = "StarkScan"                           # Block explorer service used to display links to transaction details

[sncast.predifi]
account = "predifi"
accounts-file = "/home/akshola00/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://free-rpc.nethermind.io/sepolia-juno/"

# 0x4287a17fc57912782dbcbf43b9cdf8b9d8133e275ded2f03bd2617c3fa1974d
[sncast.predifi2]
account = "predifi2"
accounts-file = "/home/codespace/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://free-rpc.nethermind.io/sepolia-juno/"
